version: '3.4'

services:
  mysql:
    image: ubuntu/mysql:${MYSQL_VERSION:-8.0-20.04_edge}
    restart: on-failure
    container_name: mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/db/:/docker-entrypoint-initdb.d/:rw
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
    networks:
      - flask_mysql_app_network

volumes:
  mysql-data:

networks:
  flask_mysql_app_network:
    driver: bridge